name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # replace 'main' with the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: java-app

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thirty-tfg'  # replace 'your-app-name' with the name of your Azure App Service
        package: './java-app.war'
